### ISSUE TITLE
Update azure-pipelines.yml with agency-specific variables

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/eligibility-server#291]
From the Terraform init task in [`azure-pipelines.yml`](https://github.com/cal-itp/eligibility-server/blob/dev/terraform/pipeline/azure-pipelines.yml#L51):

```yml
- task: TerraformTaskV3@3
  displayName: Terraform init
  inputs:
    provider: azurerm
    command: init
    workingDirectory: "$(System.DefaultWorkingDirectory)/terraform"
    # https://developer.hashicorp.com/terraform/tutorials/automation/automate-terraform#automated-terraform-cli-workflow
    commandOptions: -input=false
    # service connection
    backendServiceArm: deployer
    # needs to match main.tf
    backendAzureRmResourceGroupName: courtesy-cards-eligibility-terraform
    backendAzureRmStorageAccountName: courtesycardsterraform
    backendAzureRmContainerName: tfstate
    backendAzureRmKey: terraform.tfstate
```

We need to variablize the following inputs:

- [x] `backendAzureRmResourceGroupName: courtesy-cards-eligibility-terraform`
- [x] `backendAzureRmStorageAccountName: courtesycardsterraform`

While keeping the above comment in mind:

```yml
# needs to match main.tf
```

See #292 

## Additional context

Will be impacted by the work from #284, but ideally here we don't care about _how_ the pipeline is triggered, just where the input values come from.
