### ISSUE TITLE
Setup nightly app restart for SBMTD server

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/eligibility-server#362]
This is done through the Azure Dev Ops UI, under Pipelines > Releases.

Look at MST for examples.

Maybe in the future we can figure out how to encode this into a YAML file or similar?

**Comment by thekaveman** [comment]
@angela-tran I'm not seeing the `Releases` option under `Pipelines` for the SBMTD org? I do see it in MST. Could this be a permissions thing?

I'll note that I am an admin of the DevOps project in MST:

![image](https://github.com/cal-itp/eligibility-server/assets/1783439/5c47a0dd-d6ec-42fb-8327-ff9f032e7ce1)

But not in SBMTD:

![image](https://github.com/cal-itp/eligibility-server/assets/1783439/5be9bc3c-e937-4269-a448-e3fb066d48c5)

**Comment by angela-tran** [comment]
Apparently it's a setting under `Pipelines` to enable/disable this feature

![image](https://github.com/cal-itp/eligibility-server/assets/25497886/9306a688-4184-4e5d-b978-d9a25a42280c)

I actually think this might be the point where it makes sense to go ahead and define this as a YAML pipeline, using MST's release pipeline as a reference. The YAML pipeline would have 3 tasks that look something like this:
```
- task: AzureAppServiceManage@0
  displayName: 'Restart Azure App Service: mst-courtesy-cards-eligibility-server-test'
  inputs:
    azureSubscription: deployer
    Action: 'Restart Azure App Service'
    WebAppName: 'mst-courtesy-cards-eligibility-server-test'
```

There is more documentation on `AzureAppServiceManage` here: https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/azure-app-service-manage-v0?view=azure-pipelines

Do you think this makes sense to do now, or should we just focus on getting it set up and working?
