### ISSUE TITLE
Simplify tag fetching in CI

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/eligibility-server#401]
@angela-tran this was a great find and fix!

I think it can be done a bit simpler directly from the [`actions/checkout@v4` step](https://github.com/actions/checkout?tab=readme-ov-file#usage):

```yml
- uses: actions/checkout@v4
  with:
    # Number of commits to fetch. 0 indicates all history for all branches and tags.
    # Default: 1
    fetch-depth: 0 
    
    # Whether to fetch tags, even if fetch-depth > 0.
    # Default: false
    fetch-tags: true
```

Maybe the `fetch-depth` doesn't matter as much when we force `fetch-tags`, which would be even simpler!

We also noticed this as a potential problem for the auto release notes generation happening in the [`release`](https://github.com/cal-itp/eligibility-server/blob/dev/.github/workflows/release.yml) workflow

## Acceptance criteria

- [ ] The [`docker-publish.yml`](https://github.com/cal-itp/eligibility-server/blob/dev/.github/workflows/docker-publish.yml) workflow is updated with the above syntax
- [ ] The [`release`](https://github.com/cal-itp/eligibility-server/blob/dev/.github/workflows/release.yml) workflow is updated with the above syntax

_Originally posted by @thekaveman in https://github.com/cal-itp/eligibility-server/issues/392#issuecomment-1881864030_
