### ISSUE TITLE
Add GitHub Action to build/publish Docker image

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/eligibility-server#7]
## Background

The [docker-compose.yml](https://github.com/cal-itp/benefits/blob/dev/localhost/docker-compose.yml) over in `benefits`  defines the `server` service and uses a local build path when the image doesn't yet exist on the machine:

```yaml
server:
  build: ./server #<-- build the contents of the local ./server directory (which contains a Dockerfile)
  image: eligibility_verification_server:dev
```

Once the server code is refactored out of that repository and into this one, a local build path won't work anymore.

## Proposal

[GitHub Container Registry](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry) can be used to host Docker images, which can be built and published automatically via GitHub Actions.

* [ ] Set up a publishing workflow for this repository that builds and publishes the server app in a Docker image to GitHub
* [ ] In `benefits`, update the `server` service to use the new image directly without a build.
